[package]
name = "conway"
version = "0.1.0"
authors = ["Andy <19520383+LeCyberDucky@users.noreply.github.com>"]
edition = "2018"

[dependencies]
iced = { version = "0.2.0", features = ["image", "canvas", "tokio", "debug"] }
rand = "0.8.0"
crossbeam-channel = "0.5.0"
anyhow = "1.0.37"
